#!/usr/bin/env python3
"""commit_prophecy_authors.py — stage + commit World Monitor's richer authored
causal prophecies.

The scheduled World Monitor prophecy job runs a causal-inference LLM pass over
the dashboard's OWN live Intel headlines (NOT the pi News & Prophecy page) and
stages the result as JSON at the STAGE path. This script validates that JSON
against the schema the dashboard renderer expects, writes it as
`prophecy-authors.js` (window.PROPHECIES_AUTHORED + _STAMP), and optionally
commits + pushes the world-monitor repo.

The dashboard renders this richer file while it is fresh (a few hours), then
falls back to the always-on in-browser live engine (live-prophesy.js). So this
file is an optional quality layer on top of a guaranteed-live fallback.

Usage:
    python3 commit_prophecy_authors.py [--commit]
"""
import json, os, re, subprocess, sys, datetime

HOME = os.path.expanduser('~')
STAGE = os.path.join(HOME, 'wm_prophecy_stage.json')   # what the LLM job writes
OUT = os.path.join(HOME, 'world-monitor', 'prophecy-authors.js')
REPO = os.path.join(HOME, 'world-monitor')

REQUIRED = ['emoji', 'title', 'short', 'tag', 'cls', 'kw', 'cause', 'bullets',
            'verse', 'verseSrc', 'hinge']

def clean(s):
    return re.sub(r'\s+', ' ', (s or '')).strip()

def validate(recs):
    if not isinstance(recs, list) or not recs:
        raise SystemExit('STAGE JSON must be a non-empty list of prophecy records')
    if len(recs) > 8:
        raise SystemExit('too many records (%d); cap at 8' % len(recs))
    for i, r in enumerate(recs):
        if not isinstance(r, dict):
            raise SystemExit('record %d not an object' % i)
        for k in REQUIRED:
            if k not in r:
                raise SystemExit('record %d missing "%s"' % (i, k))
        if not isinstance(r['kw'], list) or not r['kw']:
            raise SystemExit('record %d kw must be a non-empty list' % i)
        if not isinstance(r['bullets'], list) or not r['bullets']:
            raise SystemExit('record %d bullets must be a non-empty list' % i)
        for k in ['emoji', 'title', 'tag', 'cls', 'cause', 'verse', 'verseSrc', 'hinge']:
            if not clean(r.get(k)):
                raise SystemExit('record %d %s is empty' % (i, k))
    return True

def main():
    if not os.path.exists(STAGE):
        print('STAGE not found:', STAGE); sys.exit(1)
    try:
        data = json.load(open(STAGE, encoding='utf-8'))
    except Exception as e:
        print('STAGE JSON parse error:', e); sys.exit(1)
    validate(data)
    # normalise + add a readable updated stamp
    stamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    records = [{
        'emoji': clean(r['emoji']),
        'title': clean(r['title']),
        'short': clean(r['short']) or clean(r['title'])[:115],
        'tag': clean(r['tag']),
        'cls': clean(r['cls']),
        'kw': [str(k).lower().strip() for k in r['kw'] if str(k).strip()],
        'cause': clean(r['cause']),
        'bullets': [clean(b) for b in r['bullets'] if clean(b)],
        'verse': clean(r['verse']),
        'verseSrc': clean(r['verseSrc']),
        'hinge': clean(r['hinge']),
    } for r in data]
    content = (
        '// World Monitor — richer authored causal prophecies, generated by the\n'
        '// scheduled causal-analysis job from World Monitor\'s OWN live Intel feed\n'
        '// (NOT the pi News & Prophecy page). Rendered while fresh, with the\n'
        '// in-browser live engine (live-prophesy.js) as the always-on fallback.\n'
        '// AUTO-GENERATED — do not edit by hand.\n'
        'window.PROPHECIES_AUTHORED = ' + json.dumps(records, ensure_ascii=False, indent=1) + ';\n\n'
        "window.PROPHECIES_AUTHORED_STAMP = '" + stamp + "';\n"
    )
    prev = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if prev == content:
        print('prophecy-authors.js unchanged (%d records, %s)' % (len(records), stamp))
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote prophecy-authors.js:', len(records), 'records, stamp', stamp)
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'prophecy-authors.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'prophecy: authored causal analysis over worldmonitor live intel (%s)' % stamp[:10]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0

if __name__ == '__main__':
    sys.exit(main())
