#!/usr/bin/env python3
"""fetch_penny.py — snapshot sub-$5 US and Canadian stocks into penny.js.

The dashboard's Penny Stocks panel fetches this live in the browser (the
TradingView scanner answers a text/plain POST with CORS allowed, so no proxy is
needed). This snapshot is the fallback for the cases where that call cannot be
made — offline, a blocked network, or the scanner rate-limiting a visitor — so
the panel still shows real, recent data instead of nothing.

The universe is the scanner's own, not a hand-typed ticker list:
    https://scanner.tradingview.com/america/scan   (USD)
    https://scanner.tradingview.com/canada/scan    (CAD)
filtered to a price band and a minimum share volume, ranked by volume.

Writes window.PENNY = { _updated, source, rule, usd:[…], cad:[…] } with each row
{sym, exch, name, price, chg, vol, cur, tv}.

Usage:
    python3 fetch_penny.py            # write penny.js (only when changed)
    python3 fetch_penny.py --commit   # write + commit + push
"""
import datetime, json, os, subprocess, sys, urllib.request

HOME = os.path.expanduser('~')
REPO = os.environ.get('WM_REPO_DIR') or os.path.join(HOME, 'world-monitor')
OUT = os.path.join(REPO, 'penny.js')
SCAN = 'https://scanner.tradingview.com/%s/scan'
COLS = ['name', 'description', 'close', 'change', 'volume', 'currency', 'exchange']
# Penny band + liquidity floor. Canadian books are thinner, so the floor is lower.
MARKETS = [
    ('america', 'usd', 0.01, 4.99, 500_000, 14),
    ('canada',  'cad', 0.01, 4.99, 100_000, 14),
]
UA = {'User-Agent': 'WorldMonitor-PennyFetcher/1.0 (public TradingView scanner API)',
      'Accept': 'application/json', 'Origin': 'https://worldmonitor.thealpha-secret.xyz'}


def scan(market, lo, hi, minvol, keep):
    body = {
        'filter': [
            {'left': 'close',  'operation': 'greater', 'right': lo},
            {'left': 'close',  'operation': 'less',    'right': hi},
            {'left': 'volume', 'operation': 'greater', 'right': minvol},
            # type=stock keeps leveraged ETPs out: GraniteShares/Leverage Shares
            # products are 'fund' in the scanner but price under $5 like a penny
            # stock, and "2x Short NVDA" is not what this panel is for.
            {'left': 'type',   'operation': 'equal',   'right': 'stock'},
        ],
        'options': {'lang': 'en'},
        'columns': COLS,
        'sort': {'sortBy': 'volume', 'sortOrder': 'desc'},
        'range': [0, 60],
    }
    req = urllib.request.Request(SCAN % market, data=json.dumps(body).encode(),
                                 headers=dict(UA, **{'Content-Type': 'text/plain'}))
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.loads(r.read().decode('utf-8', 'ignore'))
    rows = []
    for item in data.get('data') or []:
        sym, name, price, chg, vol, cur, exch = (list(item.get('d') or []) + [None] * 7)[:7]
        if not sym or price is None or cur is None:
            continue
        rows.append({
            'sym': sym, 'exch': exch or '', 'name': (name or '').strip(),
            'price': round(float(price), 4), 'chg': round(float(chg or 0), 2),
            'vol': int(vol or 0), 'cur': cur,
            'tv': 'https://www.tradingview.com/symbols/%s/' % (item.get('s') or '').replace(':', '-'),
        })
    # The scanner's own sort is by volume, but re-sort so a client-side merge can
    # never reorder the list by accident.
    rows.sort(key=lambda r: -r['vol'])
    return rows[:keep]


def main():
    out = {'usd': [], 'cad': []}
    ok = 0
    for market, key, lo, hi, minvol, keep in MARKETS:
        try:
            rows = scan(market, lo, hi, minvol, keep)
        except Exception as e:
            print('%s scan failed: %s' % (market, e))
            rows = []
        if rows:
            ok += 1
        out[key] = rows
        print('%-8s %d rows (top: %s)' % (market, len(rows),
              ', '.join('%s %.3f (%s)' % (r['sym'], r['price'], r['exch']) for r in rows[:3])))
    if not ok:
        print('every scan failed — leaving penny.js untouched')
        return 1
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    data = {
        '_updated': stamp,
        'source': 'TradingView scanner · delayed quotes',
        'rule': 'common stock, US$0.01–4.99 (USD) / C$0.01–4.99 (CAD), ranked by volume',
        'usd': out['usd'],
        'cad': out['cad'],
    }
    content = ('// AUTO-GENERATED by fetch_penny.py — do not edit by hand.\n'
               '// Sub-$5 US + Canadian listings from the TradingView scanner; the panel\n'
               '// refreshes live in the browser and falls back to this snapshot.\n'
               'window.PENNY = ' + json.dumps(data, ensure_ascii=False) + ';\n')

    def sig(d):
        return json.dumps([[r['sym'], r['price'], r['vol']] for r in (d.get('usd') or []) + (d.get('cad') or [])])

    prev = {}
    if os.path.exists(OUT):
        try:
            prev = json.loads(open(OUT, encoding='utf-8').read().split('=', 1)[1].rsplit(';', 1)[0])
        except Exception:
            prev = {}
    if sig(data) == sig(prev):
        print('penny.js unchanged (%d usd + %d cad) — %s' % (len(out['usd']), len(out['cad']), stamp))
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote penny.js: %d USD + %d CAD rows @ %s' % (len(out['usd']), len(out['cad']), stamp))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'penny.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'penny: sub-$5 US/CAD snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
