#!/usr/bin/env python3
"""fetch_floods.py — pull live flood alerts into floods.js.

Two real, keyless sources:

  * GDACS (Global Disaster Alert and Coordination System) flood event list —
    worldwide, with coordinates and Green/Orange/Red alert levels. This is the
    primary source; it is what makes the flood layer genuinely global.
        https://www.gdacs.org/gdacsapi/api/events/geteventlist/SEARCH?eventlist=FL
  * NOAA / NWS active flood warnings (US backfill, adds live local detail) —
        https://api.weather.gov/alerts/active?event=Flood Warning

GDACS sends no CORS headers, so this runs server-side and writes `floods.js`
(window.FLOODS), which the dashboard reads same-origin. Run on an interval via cron.

Usage:
    python3 fetch_floods.py            # write floods.js in place (if changed)
    python3 fetch_floods.py --commit   # write + commit + push (only when changed)
"""
import datetime, json, os, subprocess, sys, urllib.request, urllib.error

HOME = os.path.expanduser('~')
OUT = os.path.join(HOME, 'world-monitor', 'floods.js')
REPO = os.path.join(HOME, 'world-monitor')
GDACS = 'https://www.gdacs.org/gdacsapi/api/events/geteventlist/SEARCH?eventlist=FL'
NWS = 'https://api.weather.gov/alerts/active?event=Flood%20Warning'
TOTAL_CAP = 120
UA = {'User-Agent': 'WorldMonitor-FloodFetcher/1.0 (public GDACS + NOAA NWS open data)',
      'Accept': 'application/json, application/geo+json, */*'}


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode('utf-8', 'ignore'))


def parse_gdacs(d):
    out = []
    for f in (d.get('features') or [])[:TOTAL_CAP]:
        try:
            p = f.get('properties') or {}
            lon, lat = (f.get('geometry') or {}).get('coordinates', [None, None])[:2]
            if lat is None or lon is None:
                continue
            url = p.get('url') or {}
            out.append({
                'id': 'FL%d' % (p.get('eventid') or 0),
                'name': (p.get('name') or p.get('description') or 'Flood').strip(),
                'level': (p.get('alertlevel') or 'Green').strip(),
                'score': p.get('alertscore'),
                'country': (p.get('country') or '').strip(),
                'lat': round(float(lat), 4),
                'lng': round(float(lon), 4),
                'from': (p.get('fromdate') or '')[:10],
                'to': (p.get('todate') or '')[:10],
                'modified': p.get('datemodified') or '',
                'report': url.get('report') or '',
                'glide': p.get('glide') or '',
                'src': 'GDACS',
            })
        except Exception:
            continue           # one malformed event must not kill the pass
    return out


def parse_nws(d):
    out = []
    for f in (d.get('features') or [])[:80]:
        try:
            p = f.get('properties') or {}
            area = (p.get('areaDesc') or '').strip()
            out.append({
                'id': (f.get('id') or '')[:64],
                'name': (p.get('event') or 'Flood Warning').strip() + ((' — ' + area) if area else ''),
                'level': 'Red' if (p.get('severity') or '').lower() in ('severe', 'extreme') else 'Orange',
                'severity': p.get('severity') or '',
                'sent': p.get('sent') or '',
                'src': 'NWS',
            })
        except Exception:
            continue
    return out


def main():
    gdacs, nws = [], []
    ok = 0
    try:
        gdacs = parse_gdacs(fetch(GDACS)); ok += 1
    except Exception as e:
        print('GDACS fetch failed:', e)
    try:
        nws = parse_nws(fetch(NWS)); ok += 1
    except Exception as e:
        print('NWS fetch failed:', e)
    if not gdacs and not nws:
        print('parsed 0 flood alerts from both sources — aborting to avoid clobbering')
        sys.exit(1)

    by_level = {lvl: sum(1 for e in gdacs if e['level'] == lvl) for lvl in ('Red', 'Orange', 'Green')}
    countries = sorted({e['country'] for e in gdacs if e['country']})
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    data = {
        '_updated': stamp,
        'source': 'GDACS + NOAA/NWS',
        'sources': '%d/2 feeds' % ok,
        'count': len(gdacs) + len(nws),
        'global': len(gdacs),
        'usWarnings': len(nws),
        'red': by_level['Red'],
        'orange': by_level['Orange'],
        'green': by_level['Green'],
        'countries': countries,
        'events': gdacs,
        'usEvents': nws[:40],
    }
    content = ('// AUTO-GENERATED by fetch_floods.py — do not edit by hand.\n'
               '// Live flood alerts: GDACS global event list + NOAA/NWS US flood warnings.\n'
               'window.FLOODS = ' + json.dumps(data, ensure_ascii=False) + ';\n')

    # change detection: ignore the moving timestamp, compare the actual event set
    def sig(d):
        return json.dumps([(e['id'], e['level']) for e in d.get('events', [])] +
                          [(e['id'], e['level']) for e in d.get('usEvents', [])], sort_keys=True)
    prev = {}
    if os.path.exists(OUT):
        try:
            prev = json.loads(open(OUT, encoding='utf-8').read().split('=', 1)[1].rsplit(';', 1)[0])
        except Exception:
            prev = {}
    if sig(data) == sig(prev):
        print('floods.js unchanged (%d global, %d US, %s)' % (len(gdacs), len(nws), stamp))
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote floods.js: %d global (Red %d / Orange %d) + %d US warnings, %d countries, %s'
          % (len(gdacs), by_level['Red'], by_level['Orange'], len(nws), len(countries), stamp))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'floods.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'flood: GDACS/NWS flood snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
