#!/usr/bin/env python3
"""fetch_quakes.py — pull live seismic activity (USGS earthquake feeds) into quakes.js.

USGS publishes keyless GeoJSON summary feeds that are updated within minutes of an
event:

    https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/<window>.geojson

We merge the M2.5+ past-day feed (dense, local/regional events) with the M4.5+
past-week feed (significant events, incl. anything that dropped off the day feed)
so the map shows both current tremors and the week's notable quakes. Duplicates
across the two feeds are removed by USGS event id.

The dashboard reads `quakes.js` same-origin and draws each event as a magnitude-
sized circle marker on the World map. Run on an interval via cron.

Usage:
    python3 fetch_quakes.py            # write quakes.js in place (if changed)
    python3 fetch_quakes.py --commit   # write + commit + push (only when changed)
"""
import datetime, json, os, subprocess, sys, urllib.request

HOME = os.path.expanduser('~')
OUT = os.path.join(HOME, 'world-monitor', 'quakes.js')
REPO = os.path.join(HOME, 'world-monitor')
BASE = 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/'
FEEDS = ['2.5_day.geojson', '4.5_week.geojson']
# Hard caps so one very active day cannot bloat the committed snapshot. Sorted
# newest-first before the cut, so the cap only ever trims old events.
PER_FEED_CAP, TOTAL_CAP = 120, 160
UA = {'User-Agent': 'WorldMonitor-QuakeFetcher/1.0 (public USGS GeoJSON summary feeds)',
      'Accept': 'application/geo+json, application/json, */*'}


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode('utf-8', 'ignore'))


def parse(feed, items):
    out = []
    for f in (items or [])[:PER_FEED_CAP]:
        try:
            lon, lat, depth = (f.get('geometry') or {}).get('coordinates', [None, None, None])[:3]
            p = f.get('properties') or {}
            if lat is None or lon is None or p.get('mag') is None:
                continue
            out.append({
                'id': f.get('id') or p.get('code') or '',
                'mag': round(float(p['mag']), 1),
                'place': (p.get('place') or 'Location unknown').strip(),
                'lat': round(float(lat), 4),
                'lng': round(float(lon), 4),
                'depth': round(float(depth), 1) if depth is not None else None,
                'ts': int(p.get('time') or 0),
                'url': p.get('url') or '',
                'tsunami': 1 if p.get('tsunami') else 0,
                'alert': p.get('alert') or '',
                'felt': p.get('felt') or 0,
                'src': feed.split('.')[0],          # 2.5_day / 4.5_week
            })
        except Exception:
            continue        # one malformed event must not kill the pass
    return out


def depth_is_shallow(d):
    return isinstance(d, (int, float)) and d < 70


def main():
    merged, ok = {}, 0
    for name in FEEDS:
        try:
            data = fetch(BASE + name)
            events = parse(name, data.get('features'))
        except Exception as e:
            print('feed %s failed: %s' % (name, e))
            events = []
        if events:
            ok += 1
        for e in events:
            if e['id'] and e['id'] not in merged:
                merged[e['id']] = e
    if not merged:
        print('parsed 0 quakes across %d feeds — aborting to avoid clobbering' % len(FEEDS))
        sys.exit(1)
    quakes = sorted(merged.values(), key=lambda q: -q['ts'])[:TOTAL_CAP]
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    strongest = max(quakes, key=lambda q: q['mag'])
    data = {
        '_updated': stamp,
        'source': 'USGS',
        'sources': '%d/%d feeds' % (ok, len(FEEDS)),
        'count': len(quakes),
        'maxMag': strongest['mag'],
        'maxPlace': strongest['place'],
        'tsunamiFlags': sum(1 for q in quakes if q['tsunami']),
        'quakes': quakes,
    }
    content = ('// AUTO-GENERATED by fetch_quakes.py — do not edit by hand.\n'
               '// Live USGS seismic summary (M2.5+ past day merged with M4.5+ past week).\n'
               'window.QUAKES = ' + json.dumps(data, ensure_ascii=False) + ';\n')
    # Change detection: a fresh stamp alone must not spam git.
    def sig(d):
        return json.dumps([(q['id'], q['mag']) for q in d.get('quakes', [])])
    prev = {}
    if os.path.exists(OUT):
        try:
            prev = json.loads(open(OUT, encoding='utf-8').read().split('=', 1)[1].rsplit(';', 1)[0])
        except Exception:
            prev = {}
    if sig(data) == sig(prev):
        print('quakes.js unchanged (%d quakes, max M%s, %s)' % (len(quakes), strongest['mag'], stamp))
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote quakes.js: %d quakes, %s, max M%s %s' %
          (len(quakes), data['sources'], strongest['mag'], strongest['place'][:40]))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'quakes.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'seismic: USGS quake snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
