#!/usr/bin/env python3
"""fetch_fiatleak.py — scrape fiatleak.com's live market movers into a static file.

FiatLeak (fiatleak.com) sends no CORS and exposes no public JSON API, so it cannot
be fetched from the browser. This scraper pulls it server-side (where CORS does
not apply), parses the rendered asset grid (crypto + US stocks with price and 24h
change), and writes `fiatleak.js` (window.FIATLEAK) that the dashboard reads
same-origin. Run hourly via the 'FiatLeak Market Scrape' cron.

Usage:
    python3 fetch_fiatleak.py            # write fiatleak.js in place (if changed)
    python3 fetch_fiatleak.py --commit   # write + commit + push
"""
import json, os, re, subprocess, sys, datetime, urllib.request

HOME = os.path.expanduser('~')
OUT = os.path.join(HOME, 'world-monitor', 'fiatleak.js')
REPO = os.path.join(HOME, 'world-monitor')
URL = 'https://fiatleak.com/'
UA = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36'}

STABLECOINS = {'USDT', 'USDC', 'BUSD', 'DAI', 'TUSD', 'FRAX', 'PYUSD', 'USDE', 'USD1'}

def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode('utf-8', 'ignore')

def parse_items(html):
    """Every rendered asset (crypto + US stock) is an <a class="cryptocurrency_item">
    containing a .ticker and a .price-wrapper with .price and .delta _up/_down."""
    rx = re.compile(
        r'<span class="ticker">([a-z0-9.]+)</span>'
        r'[\s\S]*?<span class="price"[^>]*>\$([0-9][0-9,]*(?:\.\d+)?)'
        r'<span class="suffix">.*?</span></span>'
        r'<span class="delta (_up|_down)">([^<]+)</span>')
    items = {}
    for m in rx.finditer(html):
        sym = m.group(1).upper()
        if sym in items:
            continue
        price = m.group(2)
        try:
            pct = float(m.group(4).strip().rstrip('%'))
        except ValueError:
            continue
        if m.group(3) == '_down':
            pct = -abs(pct)
        else:
            pct = abs(pct)
        items[sym] = [price, round(pct, 2)]
    return items

def main():
    try:
        html = fetch(URL)
    except Exception as e:
        print('fetch failed:', e); sys.exit(1)
    assets = parse_items(html)
    if len(assets) < 10:
        print('parse yielded too few assets (%d) — aborting to avoid clobbering' % len(assets)); sys.exit(1)
    movers = {s: a for s, a in assets.items() if s not in STABLECOINS}
    gains = sorted([(s, a[1]) for s, a in movers.items() if a[1] > 0], key=lambda x: -x[1])
    losses = sorted([(s, a[1]) for s, a in movers.items() if a[1] < 0], key=lambda x: x[1])
    marquee = ['BTC', 'ETH', 'SOL', 'XRP', 'ADA', 'BNB', 'DOGE', 'LINK',
               'AAPL', 'MSFT', 'NVDA', 'TSLA', 'META', 'GOOGL', 'AMZN', 'AMD']
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    data = {
        '_updated': stamp,
        'assets': assets,
        'topGainers': gains[:8],
        'topLosers': losses[:6],
        'breadth': {'g': len(gains), 'l': len(losses)},
        'marquee': {s: assets[s] for s in marquee if s in assets},
    }
    content = ('// AUTO-GENERATED by fetch_fiatleak.py — do not edit by hand.\n'
               'window.FIATLEAK = ' + json.dumps(data, ensure_ascii=False) + ';\n')
    prev = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if prev == content:
        print('fiatleak.js unchanged (%d assets, %s)' % (len(assets), stamp)); return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote fiatleak.js: %d assets, %d gainers / %d losers, %s'
          % (len(assets), len(gains), len(losses), stamp))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'fiatleak.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'market: fiatleak movers snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0

if __name__ == '__main__':
    sys.exit(main())
