#!/usr/bin/env python3
"""fetch_amber.py — pull NCMEC missing-children alert cases into a static file.

NCMEC (National Center for Missing & Exploited Children) publishes an XML/RSS of
current missing-children alert cases. It sends no CORS, so it cannot be fetched
from the browser — this scraper pulls it server-side (where CORS does not apply),
geocodes each case's "Missing From CITY, STATE" to lat/lng via OpenStreetMap
Nominatim, and writes `amber.js` (window.AMBER) that the dashboard reads
same-origin. Run on an interval via cron.

COVERAGE NOTE: this is the genuine NCMEC public feed — US-anchored missing-child
alert cases (some cases are runaways/family situations, not all are AMBER
abductions). It is intentionally labelled as NCMEC data, never 'worldwide'.

Usage:
    python3 fetch_amber.py            # write amber.js in place (if changed)
    python3 fetch_amber.py --commit   # write + commit + push
"""
import json, os, re, subprocess, sys, datetime, time, urllib.request, urllib.parse

HOME = os.path.expanduser('~')
OUT = os.path.join(HOME, 'world-monitor', 'amber.js')
REPO = os.path.join(HOME, 'world-monitor')
FEED = ('https://www.missingkids.org/missingkids/servlet/XmlServlet'
        '?act=rss&LanguageCountry=en_US&orgPrefix=NCMC')
GEO = 'https://nominatim.openstreetmap.org/search'
UA = {'User-Agent': 'WorldMonitor-AmberFetcher/1.0 (openstreetmap usage policy) contact: admin@thealpha-secret.xyz'}

def fetch(url, data=None):
    req = urllib.request.Request(url, data=data, headers=UA)
    with urllib.request.urlopen(req, timeout=25) as r:
        return r.read().decode('utf-8', 'ignore')

def geocode(city, state):
    q = '%s, %s, USA' % (city, state)
    url = GEO + '?' + urllib.parse.urlencode({'q': q, 'format': 'json', 'limit': 1})
    try:
        j = json.loads(fetch(url))
        if j and j[0].get('lat') and j[0].get('lon'):
            return (float(j[0]['lat']), float(j[0]['lon']))
    except Exception:
        pass
    return None

def clean(text):
    # XML entities + CR/LF junk; collapse whitespace
    text = text.replace('&#xd;', ' ').replace('&#x2019;', "'").replace('&amp;', '&')
    return re.sub(r'\s+', ' ', text).strip()

def parse_feed(xml):
    out = []
    for m in re.finditer(r'<item>(.*?)</item>', xml, re.S):
        it = m.group(1)
        title = clean(re.search(r'<title>(.*?)</title>', it, re.S).group(1))
        guid = clean(re.search(r'<guid[^>]*>(.*?)</guid>', it, re.S).group(1))
        desc = clean(re.search(r'<description>(.*?)</description>', it, re.S).group(1))
        link = clean(re.search(r'<link>(.*?)</link>', it, re.S).group(1))
        # NCMEC publishes these over http; the site serves https fine, so upgrade
        # to avoid a redirect hop and any mixed-content warnings in the UI.
        link = re.sub(r'^http://', 'https://', link)
        photo = None
        en = re.search(r'<enclosure[^>]*url="([^"]+)"', it)
        if en: photo = en.group(1).replace('http://', 'https://')
        # title: ": First Last (ST)"; desc holds "Name, Age Now: N, Missing: DATE. Missing From CITY, ST."
        age = None
        name = title.lstrip(': ').strip()
        st_abbr = ''
        if title.endswith(')') and ' (' in title:
            st_abbr = title.rsplit('(', 1)[1].rstrip(')').strip()
            name = name[:-(len(st_abbr)+3)].strip()   # drop the trailing " (ST)"
        am = re.search(r'Age Now:\s*(\d+)', desc)
        if am: age = int(am.group(1))
        fm = re.search(r'Missing From\s*([^.]*)\.', desc)
        m1 = re.search(r'Missing:\s*([^.]*?)\s*\.\s*Missing From', desc)
        mdate = m1.group(1).strip() if m1 else None
        loc = fm.group(1).strip() if fm else None
        # "CITY, ST" split on last comma
        city = state = None
        if loc:
            parts = [p.strip() for p in loc.split(',')]
            city = parts[0]
            if len(parts) > 1:
                state = parts[1].split()[0] if parts[1] else None
        out.append(dict(name=name, guid=guid, age=age, missing=mdate,
                        loc=loc, city=city, state=state, stateAbbr=st_abbr,
                        link=link, photo=photo, desc=desc))
    return out

def main():
    try:
        xml = fetch(FEED)
    except Exception as e:
        print('feed fetch failed:', e); sys.exit(1)
    cases = parse_feed(xml)
    if not cases:
        print('parsed 0 cases — aborting to avoid clobbering'); sys.exit(1)
    # geocode each (respect Nominatim ~1 req/s)
    for i, c in enumerate(cases):
        if c.get('city') and c.get('state'):
            ll = geocode(c['city'], c['state'])
            if ll: c['lat'], c['lng'] = ll
            time.sleep(1.1)
    ngeo = sum(1 for c in cases if c.get('lat'))
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    data = {'_updated': stamp, 'source': 'NCMEC', 'coverage': 'US-anchored',
            'geocoded': ngeo, 'cases': cases}
    content = ('// AUTO-GENERATED by fetch_amber.py — do not edit by hand.\n'
               '// Real NCMEC missing-children alert cases (US-anchored), geocoded.\n'
               'window.AMBER = ' + json.dumps(data, ensure_ascii=False) + ';\n')
    prev = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if prev == content:
        print('amber.js unchanged (%d cases, %d geocoded, %s)' % (len(cases), ngeo, stamp)); return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote amber.js: %d cases, %d geocoded, %s' % (len(cases), ngeo, stamp))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'amber.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'amber: NCMEC missing-child alert snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0

if __name__ == '__main__':
    sys.exit(main())
