#!/usr/bin/env python3
"""fetch_worldpop.py — snapshot the World Bank world-population figure into worldpop.js.

The dashboard's World Population card fetches the World Bank API live in the browser
(keyless, CORS `*`). This snapshot is the fallback for when that call cannot be made,
so the card still shows the real published figure instead of nothing.

It stores the two numbers the card needs and nothing else:
  * SP.POP.TOTL for WLD — the world population estimate for the latest published year
  * SP.POP.GROW for WLD — that same year's annual growth rate, in percent
The card compounds the first at the second from the estimate's reference date, and
labels the result an estimate everywhere it appears. There is no official per-second
world population feed, and this script does not pretend to produce one.

Usage:
    python3 fetch_worldpop.py            # write worldpop.js (only when changed)
    python3 fetch_worldpop.py --commit   # write + commit + push
"""
import datetime, json, os, subprocess, sys, urllib.request

HOME = os.path.expanduser('~')
REPO = os.environ.get('WM_REPO_DIR') or os.path.join(HOME, 'world-monitor')
OUT = os.path.join(REPO, 'worldpop.js')
API = 'https://api.worldbank.org/v2/country/WLD/indicator/%s?format=json&date=2015:2035&per_page=40'
UA = {'User-Agent': 'WorldMonitor-WorldPopFetcher/1.0 (public World Bank indicator API)',
      'Accept': 'application/json'}


def latest(indicator):
    req = urllib.request.Request(API % indicator, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.loads(r.read().decode('utf-8', 'ignore'))
    rows = [x for x in (data[1] or []) if x.get('value') is not None and x.get('date')]
    rows.sort(key=lambda x: -int(x['date']))
    return rows[0] if rows else None


def main():
    try:
        tot = latest('SP.POP.TOTL')
        grow = latest('SP.POP.GROW')
    except Exception as e:
        print('World Bank fetch failed: %s — leaving worldpop.js untouched' % e)
        return 1
    if not tot:
        print('no population observation returned — aborting')
        return 1
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    data = {
        '_updated': stamp,
        'base': int(tot['value']),
        'year': int(tot['date']),
        'ratePct': round(float(grow['value']), 4) if grow else None,
        'growthYear': int(grow['date']) if grow else None,
        'source': 'World Bank indicator SP.POP.TOTL / SP.POP.GROW (WLD)',
    }
    content = ('// AUTO-GENERATED by fetch_worldpop.py — do not edit by hand.\n'
               '// World Bank world-population estimate for the latest published year; the card\n'
               '// compounds it at the published annual growth rate and labels the result an estimate.\n'
               'window.WORLDPOP = ' + json.dumps(data, ensure_ascii=False) + ';\n')
    prev = {}
    if os.path.exists(OUT):
        try:
            prev = json.loads(open(OUT, encoding='utf-8').read().split('=', 1)[1].rsplit(';', 1)[0])
        except Exception:
            prev = {}
    if prev.get('base') == data['base'] and prev.get('ratePct') == data['ratePct']:
        print('worldpop.js unchanged (%s, %s, %s%%/yr) — %s' %
              (data['base'], data['year'], data['ratePct'], stamp))
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote worldpop.js: base %s (%s), growth %s%%/yr' % (data['base'], data['year'], data['ratePct']))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'worldpop.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'worldpop: World Bank estimate snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
