#!/usr/bin/env python3
"""fetch_iss.py — snapshot the ISS two-line element set (TLE) into iss.js.

The dashboard tracks the International Space Station live on the 2D map and the
3D globe. A TLE is the input to that: the browser propagates it with SGP4
(satellite.js from a CDN) and gets the station's real sub-point, altitude and
velocity every frame — no per-second API polling, and the marker glides instead
of hopping.

Sources (both keyless):
  * CelesTrak GP API   — the TLE itself (server-side fetch: CelesTrak serves no
                         CORS header, so the browser could not read it directly).
  * api.wheretheiss.at — one current-state snapshot, kept in the file as an
                         independent cross-check / fallback if the CDN module
                         or the TLE is unavailable.

A TLE stays accurate for days, so this runs a few times a day; the file is only
rewritten when the element set actually changes.

Usage:
    python3 fetch_iss.py            # write iss.js in place (if the TLE changed)
    python3 fetch_iss.py --commit   # write + commit + push (only when changed)
"""
import datetime, json, os, subprocess, sys, urllib.request

HOME = os.path.expanduser('~')
REPO = os.environ.get('WM_REPO_DIR') or os.path.join(HOME, 'world-monitor')
OUT = os.path.join(REPO, 'iss.js')
NORAD = 25544
TLE_URL = 'https://celestrak.org/NORAD/elements/gp.php?CATNR=%d&FORMAT=TLE' % NORAD
LIVE_URL = 'https://api.wheretheiss.at/v1/satellites/%d' % NORAD
UA = {'User-Agent': 'WorldMonitor-ISSFetcher/1.0 (public CelesTrak GP + wheretheiss.at APIs)',
      'Accept': 'text/plain, application/json, */*'}


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode('utf-8', 'ignore')


def parse_tle(text):
    """CelesTrak returns name/line1/line2 (3 lines); tolerate blank lines."""
    lines = [l.strip() for l in (text or '').splitlines() if l.strip()]
    name = l1 = l2 = None
    for l in lines:
        if l.startswith('1 ') and len(l) > 60:
            l1 = l
        elif l.startswith('2 ') and len(l) > 60:
            l2 = l
        elif l1 is None and l2 is None and not l[0].isdigit():
            name = l
    if not l1 or not l2:
        raise ValueError('TLE lines not found in response: %r' % (lines[:4],))
    return (name or 'ISS (ZARYA)'), l1, l2


def live_snapshot():
    """One current-state reading, used as a fallback but never as the source of
    truth — nothing here is invented: the numbers are the API's own."""
    try:
        d = json.loads(fetch(LIVE_URL))
        return {
            'lat': round(float(d['latitude']), 4),
            'lng': round(float(d['longitude']), 4),
            'alt': round(float(d['altitude']), 1),
            'vel': round(float(d['velocity']), 1),
            'visibility': d.get('visibility') or '',
            'ts': int(d.get('timestamp') or 0),
        }
    except Exception as e:
        print('live snapshot unavailable: %s' % e)
        return None


def main():
    try:
        name, tle1, tle2 = parse_tle(fetch(TLE_URL))
    except Exception as e:
        print('TLE fetch failed: %s — leaving iss.js untouched' % e)
        return 1
    epoch = tle1[18:32].strip()
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    data = {
        'name': name,
        'norad': NORAD,
        'tle1': tle1,
        'tle2': tle2,
        'epoch': epoch,
        'fetched': stamp,
        'source': 'CelesTrak GP (NORAD %d)' % NORAD,
        'live': live_snapshot(),
    }
    content = ('// AUTO-GENERATED by fetch_iss.py — do not edit by hand.\n'
               '// ISS (ZARYA) two-line element set; the browser propagates it with SGP4\n'
               '// (satellite.js) to place the station live on the map and the 3D globe.\n'
               'window.ISS = ' + json.dumps(data, ensure_ascii=False) + ';\n')
    prev = {}
    if os.path.exists(OUT):
        try:
            prev = json.loads(open(OUT, encoding='utf-8').read().split('=', 1)[1].rsplit(';', 1)[0])
        except Exception:
            prev = {}
    if prev.get('tle2') == tle2 and prev.get('tle1') == tle1:
        print('iss.js unchanged (TLE epoch %s) — %s' % (epoch, stamp))
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print('wrote iss.js: %s, TLE epoch %s, live alt %s km' %
          (name, epoch, (data['live'] or {}).get('alt', '?')))
    if '--commit' in sys.argv:
        subprocess.run(['git', '-C', REPO, 'add', 'iss.js'], check=True)
        subprocess.run(['git', '-C', REPO, 'commit', '-m',
                        'iss: CelesTrak TLE snapshot (%s)' % stamp[:16]], check=True)
        subprocess.run(['git', '-C', REPO, 'push', 'origin', 'main'], check=True)
        print('committed + pushed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
