// AUTO-GENERATED by fetch_iss.py — do not edit by hand.
// ISS (ZARYA) two-line element set; the browser propagates it with SGP4
// (satellite.js) to place the station live on the map and the 3D globe.
window.ISS = {"name": "ISS (ZARYA)", "norad": 25544, "tle1": "1 25544U 98067A   26267.14191496  .00009634  00000+0  18116-3 0  9999", "tle2": "2 25544  51.6318 170.3464 0004691 174.6338 185.4701 15.49258637587098", "epoch": "26267.14191496", "fetched": "2026-09-24 13:32 UTC", "source": "CelesTrak GP (NORAD 25544)", "live": {"lat": -13.9901, "lng": 152.9997, "alt": 419.5, "vel": 27582.0, "visibility": "eclipsed", "ts": 1790256760}};
