// AUTO-GENERATED by fetch_iss.py — do not edit by hand.
// ISS (ZARYA) two-line element set; the browser propagates it with SGP4
// (satellite.js) to place the station live on the map and the 3D globe.
window.ISS = {"name": "ISS (ZARYA)", "norad": 25544, "tle1": "1 25544U 98067A   26280.56304952  .00004213  00000+0  85268-4 0  9994", "tle2": "2 25544  51.6311 103.9669 0006810 234.3585 125.6769 15.48762857589177", "epoch": "26280.56304952", "fetched": "2026-10-07 18:40 UTC", "source": "CelesTrak GP (NORAD 25544)", "live": {"lat": 42.6719, "lng": -60.2152, "alt": 426.3, "vel": 27576.3, "visibility": "daylight", "ts": 1791398438}};
