// AUTO-GENERATED by fetch_iss.py — do not edit by hand.
// ISS (ZARYA) two-line element set; the browser propagates it with SGP4
// (satellite.js) to place the station live on the map and the 3D globe.
window.ISS = {"name": "ISS (ZARYA)", "norad": 25544, "tle1": "1 25544U 98067A   26269.39984368  .00031849  00000+0  59036-3 0  9995", "tle2": "2 25544  51.6292 159.1757 0007020 184.2024 175.8906 15.48664613587440", "epoch": "26269.39984368", "fetched": "2026-09-26 19:13 UTC", "source": "CelesTrak GP (NORAD 25544)", "live": {"lat": 50.5598, "lng": -63.5377, "alt": 425.4, "vel": 27583.1, "visibility": "daylight", "ts": 1790449985}};
