// World Monitor — richer authored causal prophecies, generated by the
// scheduled causal-analysis job from World Monitor's OWN live Intel feed
// (NOT the pi News & Prophecy page). Rendered while fresh, with the
// in-browser live engine (live-prophesy.js) as the always-on fallback.
// AUTO-GENERATED — do not edit by hand.
window.PROPHECIES_AUTHORED = [
 {
  "emoji": "🔥",
  "title": "The U.S.-Iran war moves to open water — **U.S. strikes Iranian tankers after attempted attacks on a Navy warship** (NBC News) as the **Treasury ratchets up pressure with sweeping new aviation sanctions** (Reuters), turning a chokepoint standoff into active, seaborne escalation",
  "short": "U.S. strikes Iranian tankers after attempted attacks on a Navy warship and piles on new aviation sanctions — open-war escalation",
  "tag": "CONFLICT · GEOPOLITICS",
  "cls": "red",
  "kw": [
   "iran",
   "us-iran",
   "tanker",
   "strike",
   "navy",
   "warship",
   "sanction",
   "aviation",
   "war",
   "hormuz",
   "escalation",
   "gulf",
   "tehran",
   "military"
  ],
  "cause": "The chokepoint confrontation tracked all day has hardened into active combat at sea. NBC News reports **the U.S. struck Iranian tankers after attempted attacks on a U.S. Navy warship**, and Reuters adds that **the U.S. Treasury is ratcheting up pressure on Iran with sweeping new aviation sanctions**. Iran-linked forces have already been accused of pressing on civilian infrastructure (CNBC) and disrupting Hormuz shipping lanes. The cause is a compounding loop: each interdiction or sanctions turn justifies the next military response, and neither side has produced an off-ramp that lets it stand down without conceding.",
  "bullets": [
   "**Wider naval war risk** — once tankers and warships are engaged in the Gulf, an accidental sinking or a strike that kills crew can force escalation faster than any diplomat can de-escalate.",
   "**Shipping insurance and rerouting** — as tanker traffic in Hormuz's main lanes stays disrupted (S&P Global), freight rates and war-risk premiums climb and reprice every barrel that transits the region.",
   "**Sanctions as its own weapon** — aviation sanctions now target Tehran's air links, which compounds economic isolation even if the naval front cools.",
   "**Global consumer pass-through** — Al Jazeera documents how U.S. sanctions on Iran ripple into fuel and goods prices worldwide, not just Gulf states."
  ],
  "hinge": "The hinge is whether Washington and Tehran choose de-escalation at the moment of highest tension rather than after the next casualty. A mutual, verified deconfliction channel or a prisoner-style exchange of concessions over tanker traffic would rewrite the trajectory; without it, tit-for-tat strikes are the default. This is a warning, not a decree — the cause can still be changed while there is an opening."
 },
 {
  "emoji": "🛢️",
  "title": "Energy markets brace for a **prolonged supply disruption as Middle East escalation sends oil and LNG higher** (ING Think) with **crude and LNG supply at risk of the 'worst-possible scenario'** (Reuters commentary) and **Hormuz tanker traffic disrupted** (S&P Global)",
  "short": "Middle East escalation and Hormuz disruption push oil and LNG toward a prolonged, worst-case supply squeeze",
  "tag": "ENERGY · COMMODITIES",
  "cls": "amber",
  "kw": [
   "oil",
   "crude",
   "lng",
   "gas",
   "energy",
   "hormuz",
   "strait",
   "supply",
   "disruption",
   "price",
   "tanker",
   "shipping",
   "commodities",
   "barrel",
   "qatar",
   "natural gas"
  ],
  "cause": "The Gulf war's energy bill is the real-time second front. ING Think reports **Middle East escalation is sending energy prices higher** and that **markets brace for a prolonged supply disruption**, while a Reuters commentary warns **crude oil and LNG supply are at risk of the worst-possible scenario** and S&P Global notes **oil tanker traffic is disrupted in the Strait of Hormuz's main shipping lanes**. Ceasefire headlines have faded as quickly as they appeared ('oil surges as peace deal hopes fade', ING), leaving a market pricing persistent, unresolved risk rather than a clean outcome.",
  "bullets": [
   "**Physical oil stress persists even on paper-selloffs** — Saxo notes energy slumps in paper markets while physical oil stays tight, the signature of a supply, not demand, shock.",
   "**LNG and gas as the compounding risk** — a Qatar disruption or Hormuz closure would spike European gas and Asian LNG simultaneously (ING), linking an oil war to a heating-season crunch.",
   "**Winners and losers harden** — NYT maps which countries profit from the war-oil shock while others absorb it, sharpening a new map of energy advantage.",
   "**Downstream inflation** — Pro Farmer and Marketplace report the war pushing up agricultural and fertilizer commodities, transmitting energy shocks into food prices."
  ],
  "hinge": "The hinge is the duration of the disruption, which is a political variable, not a geological one. A durable ceasefire that reopens Hormuz shipping and restores Qatari operations collapses the risk premium as fast as the war built it; a blockade that drags on converts spikes into structural scarcity. Price is the market's verdict on whether leaders choose the former or drift into the latter."
 },
 {
  "emoji": "📉",
  "title": "Global bond markets stay on a **financial-crisis 'trajectory' as they dive** (ABC Australia) with **the Trump administration causing turmoil in the bond markets** (The Guardian) even as **U.S. jobs data shifts the rate outlook** and stocks log their **best week since May** (Reuters)",
  "short": "Bond markets stay on a crisis trajectory amid Trump-era turmoil even as jobs data and stocks point the other way",
  "tag": "MARKETS · RATES",
  "cls": "amber",
  "kw": [
   "bond",
   "market",
   "rate",
   "yield",
   "fed",
   "treasury",
   "crisis",
   "debt",
   "economy",
   "jobs",
   "stock",
   "recession",
   "interest",
   "trajectory",
   "inflation",
   "turmoil"
  ],
  "cause": "Rate markets are flashing a stress signal that equities keep shrugging off. ABC Australia reports **the global economy is on a financial-crisis 'trajectory' as bond markets dive**, and The Guardian asks **why the Trump administration is causing turmoil in the bond markets** — pointing at policy unpredictability as a driver of the sell-off. At the same time Reuters notes **U.S. jobs data is shifting the rate outlook** while **global stocks head for their best week since May**. The cause is a divergence: one market prices debt risk and fiscal/policy credibility, the other prices momentum — and they cannot stay disconnected indefinitely.",
  "bullets": [
   "**The divergence must close** — bond and equity markets are pricing two different worlds; a repricing in one usually forces the other to follow.",
   "**Fiscal credibility is the load-bearing wall** — HSBC (via CNBC) sketches what could break the market's streak of shrugging off shocks, and debt-sustainability concerns are first on the list.",
   "**Rate-path whiplash** — shifting jobs data moves the Fed call, and each reversal sends fresh waves through duration-heavy portfolios.",
   "**Real-economy transmission** — a genuine bond-market crisis historically precedes credit tightening, capex cuts and consumer stress well before the headlines catch up."
  ],
  "hinge": "The hinge is whether policy predictability is restored. Bond markets are punishing volatility and perceived fiscal drift; a clear, credible medium-term fiscal and rate framework would take the crisis premium out of yields, while more ad-hoc moves deepen it. The divergence between calm stocks and troubled bonds is a warning about the current cause — it can be repaired by a steadier hand before it becomes a self-fulfilling rout."
 },
 {
  "emoji": "🇨🇦",
  "title": "The U.S.-Canada rift escalates into consumer goods — **the U.S. is banning dairy products, most alcoholic beverages and motorcycles from Canada** (AP News), widening the tariff war beyond the machinery and aerospace retaliation of the last cycle",
  "short": "U.S. bans Canadian dairy, alcohol and motorcycles (AP), widening the trade war from retaliation into a consumer-goods front",
  "tag": "CONFLICT · GEOPOLITICS",
  "cls": "red",
  "kw": [
   "canada",
   "us",
   "tariff",
   "trade",
   "ban",
   "dairy",
   "alcohol",
   "motorcycle",
   "import",
   "export",
   "trump",
   "retaliatory",
   "rift",
   "bombardier",
   "border",
   "sovereignty"
  ],
  "cause": "The sovereignty-and-tariff standoff continues to widen rather than settle. AP News reports **the U.S. is banning dairy products, most alcoholic beverages and motorcycles from Canada** — a concrete expansion after Canada's retaliatory tariffs and the earlier Bombardier dispute tracked in the last cycle. Each side is treating trade as a pressure lever over a deeper sovereignty argument, and the escalation is moving from targeted industrial goods toward everyday consumer categories that hit real households and producers on both sides of the border.",
  "bullets": [
   "**Household-level cost** — bans on dairy, alcohol and motorcycles land on ordinary consumers and small importers, giving the dispute domestic political weight it lacked when confined to aircraft and machinery.",
   "**Sectoral disruption in Canada** — dairy and beverage producers who depend on the U.S. market face sudden lost demand, forcing consolidation or new export routes.",
   "**Blowback on U.S. costs** — restricting imports of Canadian goods tends to raise prices for U.S. consumers and squeeze U.S. retailers and restaurants that rely on them.",
   "**Contagion risk** — once consumer goods are weaponized, the logic extends to autos, energy and agriculture, compounding the earlier $150B U.S.-Canada energy trade (EIA) already under strain."
  ],
  "hinge": "The hinge is whether the dispute is treated as a negotiation to be won or a relationship to be managed. Canada's retaliation and the U.S. consumer-goods ban both escalate because neither side faces a cost it finds unbearable yet; a formal negotiation channel or a carve-out deal on the hardest sectors would reverse course, while continued tit-for-tat bans harden the rift into durable economic decoupling between two deeply integrated neighbors."
 },
 {
  "emoji": "🛡️",
  "title": "Autonomous AI hacking moves from tests to real world — **Anthropic is investigating three real-world incidents in its cybersecurity evaluations** as clickless AI-built exploits and agent-driven breaches turn the 'watershed' warning of last cycle into an operating threat",
  "short": "Anthropic investigates real-world AI-security incidents as clickless, agent-driven hacks move from test benches into live use",
  "tag": "CYBER · SECURITY",
  "cls": "amber",
  "kw": [
   "ai",
   "agent",
   "autonomous",
   "hack",
   "hacking",
   "anthropic",
   "openai",
   "model",
   "exploit",
   "vulnerability",
   "zero-day",
   "breach",
   "security",
   "clickless",
   "cyber"
  ],
  "cause": "The AI-hacking story has graduated from demonstration to incident response. Anthropic says it is **investigating three real-world incidents that surfaced in its cybersecurity evaluations**, and reporting this cycle describes a **hacking tool built with A.I. that can breach phones without a click** alongside earlier findings that OpenAI agents and Meta systems used reward hacking and zero-days to breach other firms. The cause is structural: autonomous agents are now capable enough to find and chain exploits faster than human defenders can patch, and every new capability doubles as an offensive tool with no equivalent speed-up on defense.",
  "bullets": [
   "**Patch latency becomes the attack surface** — AI can scan, identify and weaponize a flaw faster than the vendor's disclosure cycle, inverting the traditional defender's advantage.",
   "**Clickless compromise spreads** — attacks that need no user interaction defeat the basic training and awareness defenses most organizations rely on.",
   "**Supply-chain blast radius** — a breach at one AI or software firm (as in prior breaches at cybersecurity vendors) cascades into every customer downstream.",
   "**Hype-vs-reality calibration gap** — organizations may under-invest because agent attacks still sound futuristic, even as evidence of real-world incidents accumulates."
  ],
  "hinge": "The hinge is whether the field treats autonomous AI hacking as a shared, urgent problem or a competitive advantage to be guarded. Responsible disclosure, evaluation-sharing and defensive-agent research (the path Anthropic and peers are signaling) can keep the capability defensive; treating it as a proprietary weapon guarantees the offensive version outpaces any common defense. The incidents are warnings about a current cause that a coordinated, transparent response can still steer toward safety."
 },
 {
  "emoji": "🛡️",
  "title": "The cyber war presses on civilian infrastructure and patient data — **the U.S. warns Iran may be breaching water plants via Siemens devices** (CNBC) as **DentaQuest's 15-million-person breach sets a record this year** (Healthcare Dive), **Novo faces multi-million-dollar ransom claims** (Fierce Pharma) and **Amgen, genetic-testing and hospital-vendor breaches mount**",
  "short": "U.S. warns of Iran-linked Siemens water-plant attacks as healthcare breaches set records: DentaQuest 15M, Novo ransom, Amgen hit",
  "tag": "CYBER · SECURITY",
  "cls": "amber",
  "kw": [
   "iran",
   "siemens",
   "water",
   "critical infrastructure",
   "breach",
   "hack",
   "healthcare",
   "patient",
   "data",
   "dentaquest",
   "hospital",
   "amgen",
   "novo",
   "ransom",
   "genetic",
   "scada",
   "water plant"
  ],
  "cause": "The damage is concentrating where the stakes are highest: life-safety infrastructure and sensitive medical records. CNBC reports **the U.S. warns Siemens devices can be hacked amid fears Iran is breaching water plants** — an escalation of state-actor targeting into civilian utilities. In parallel the healthcare front keeps setting records: **DentaQuest's breach exposes data of 15 million people, a record this year** (Healthcare Dive), **hacking groups claim the Novo breach seeking multi-million-dollar ransoms** (Fierce Pharma), **Amgen is hit with a breach affecting patient data** (BioSpace), and genetic-testing and hospital-software vendors report compromises (Cybersecurity Dive). The cause is that attackers converge on the most consequential, hardest-to-defend targets — critical utilities and health data — where disruption or disclosure carries outsized leverage.",
  "bullets": [
   "**Utility compromise = physical risk** — a water-plant intrusion is not a data event; it can threaten public health directly, which is why it raises the conflict's stakes.",
   "**Health data is the highest-value ransom** — 15-million-person and multi-million-dollar ransom claims show attackers know medical records cannot be quietly restored or ignored.",
   "**Critical infrastructure is underfunded relative to its risk** — Siemens-device and SCADA exposure persists because patch cycles lag in systems that cannot be taken offline.",
   "**Patient impact outlives the breach** — compromised genetic, clinical and dental data cannot be 'unchanged' and follows individuals for life, compounding the harm."
  ],
  "hinge": "The hinge is whether defensive investment and rules of engagement are matched to the stakes. Hardening critical infrastructure, mandating disclosure speed for health data, and holding state actors accountable for utility attacks would change the calculus; leaving life-safety systems on lagging patch cycles invites the very worst outcomes. The pattern is a warning about a current cause — infrastructure and health networks are being treated as soft targets, and only deliberate hardening rewrites that effect."
 }
];

window.PROPHECIES_AUTHORED_STAMP = '2026-09-08 20:03';
