// AUTO-GENERATED by fetch_worldpop.py — do not edit by hand.
// World Bank world-population estimate for the latest published year; the card
// compounds it at the published annual growth rate and labels the result an estimate.
window.WORLDPOP = {"_updated": "2026-09-17 21:23 UTC", "base": 8215424893, "year": 2025, "ratePct": 0.9113, "growthYear": 2025, "source": "World Bank indicator SP.POP.TOTL / SP.POP.GROW (WLD)"};
